# Generated by Django 4.1.6 on 2023-02-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Задача')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('complete', 'Завершена')], default='new', max_length=50, verbose_name='Статус задачи')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
